Drop Python 3.3 from CI
$ flake8 .
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.6/bin/flake8", line 7, in <module>
    from flake8.main.cli import main
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/flake8/main/cli.py", line 2, in <module>
    from flake8.main import application
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/flake8/main/application.py", line 17, in <module>
    from flake8.plugins import manager as plugin_manager
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/flake8/plugins/manager.py", line 5, in <module>
    import pkg_resources
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 90, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
The command "flake8 ." exited with 1.